### ISSUE TITLE
Bug on collision

### ISSUE THREAD

**Issue by FabioRomeiro** [FabioRomeiro/Kamikaze_Run#4]
**The problem:**
When the player shot more than one time, all the bullet will pass through the enemies airplanes until the first bullet get out of the screen;

**Comment by vhoyer** [comment]
isn't it fixed? I mean, I shot more than once at an enemy and it got hit by the first bullet. I can't reproduce the bug that was described.

**Comment by FabioRomeiro** [comment]
Yes, it is, I forgot to mark this issue as closed XD
